# Generated by Django 4.0.3 on 2022-04-09 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ('-created_at',)},
        ),
    ]
