# Generated by Django 4.0.3 on 2022-04-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_alter_price_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='coin',
            field=models.CharField(max_length=8),
        ),
    ]
